-- ══════════════════════════════════════════════════════════════════════════════
-- Security hardening migration — run AFTER rls_with_auth.sql + public_profiles.sql
-- Safe to re-run (uses IF NOT EXISTS / OR REPLACE / IF EXISTS).
-- ══════════════════════════════════════════════════════════════════════════════

-- ── 1. Add public_code to users ───────────────────────────────────────────────
-- Stable, non-sensitive invite identifier that replaces telegram_id in share links.
alter table public.users
  add column if not exists public_code text unique;

-- Backfill: SHA-256 hex of telegram_id so old ref_<telegram_id> links can still
-- be resolved (find_user_by_telegram_id_safe) while new links use public_code.
update public.users
  set public_code = encode(sha256((telegram_id::text)::bytea), 'hex')
  where public_code is null and telegram_id is not null;

create index if not exists users_public_code_idx on public.users (public_code);

-- ── 2. Add photo_path to moments and people ───────────────────────────────────
-- Stores the storage object path for signed-URL generation.
-- photo_url column is kept for backward compat and UI (signed URL for new uploads,
-- public URL for old records until bucket is marked private in the dashboard).
alter table public.moments
  add column if not exists photo_path text;

alter table public.people
  add column if not exists photo_path text;

-- ── 3. Drop the broad users_public_read policy (exposed telegram_id) ──────────
-- Cross-user lookups now go through SECURITY DEFINER RPC functions that expose
-- only safe fields (id, name, photo_url, public_code — never telegram_id).
drop policy if exists "users_public_read" on public.users;

-- ── 4. SECURITY DEFINER RPC functions for safe cross-user lookups ─────────────

-- Single-user lookup by id (for public profiles, stats).
create or replace function public.get_user_public(p_user_id uuid)
returns table(id uuid, name text, photo_url text, created_at timestamptz, public_code text)
language sql security definer stable as $$
  select id, name, photo_url, created_at, public_code
  from public.users
  where id = p_user_id;
$$;
grant execute on function public.get_user_public(uuid) to authenticated;

-- Batch lookup by ids (for friendships list).
create or replace function public.get_users_public(p_user_ids uuid[])
returns table(id uuid, name text, photo_url text, public_code text)
language sql security definer stable as $$
  select id, name, photo_url, public_code
  from public.users
  where id = any(p_user_ids);
$$;
grant execute on function public.get_users_public(uuid[]) to authenticated;

-- Invite resolution by public_code — never exposes telegram_id.
create or replace function public.find_user_by_public_code(p_code text)
returns table(id uuid, name text, public_code text)
language sql security definer stable as $$
  select id, name, public_code
  from public.users
  where public_code = p_code;
$$;
grant execute on function public.find_user_by_public_code(text) to authenticated;

-- Backward compat: resolve old ref_<telegram_id> deep links safely.
-- Returns only id + public_code — the telegram_id is never exposed to the client.
create or replace function public.find_user_by_telegram_id_safe(p_telegram_id bigint)
returns table(id uuid, public_code text)
language sql security definer stable as $$
  select id, public_code
  from public.users
  where telegram_id = p_telegram_id;
$$;
grant execute on function public.find_user_by_telegram_id_safe(bigint) to authenticated;

-- ── 5. Tighten storage policies: UUID folder + own-folder read ────────────────
-- Fixes the mismatch where upload used user UUID folder but RLS checked telegram_id.
-- Read is now restricted to own folder; cross-user photos are served via signed
-- URLs stored in the photo_url DB column (generated by the uploader at upload time).
--
-- NOTE: To fully privatize photo access, also mark the "photos" bucket as PRIVATE
-- in the Supabase dashboard. New uploads already use long-lived signed URLs so
-- cross-user photo display works without public bucket access. Existing records
-- with public photo_url values will remain valid until a one-time path migration.
drop policy if exists "photos_upload"  on storage.objects;
drop policy if exists "photos_read"    on storage.objects;
drop policy if exists "photos_delete"  on storage.objects;

-- Upload: first path segment must equal uploader's UUID (get_my_user_id defined in rls_with_auth.sql).
create policy "photos_upload" on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'photos'
    and (storage.foldername(name))[1] = (public.get_my_user_id())::text
  );

-- Read: own folder only. Cross-user access uses signed URLs from DB, which bypass RLS.
create policy "photos_read" on storage.objects
  for select to authenticated
  using (
    bucket_id = 'photos'
    and (storage.foldername(name))[1] = (public.get_my_user_id())::text
  );

-- Delete: own folder only.
create policy "photos_delete" on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'photos'
    and (storage.foldername(name))[1] = (public.get_my_user_id())::text
  );
